data:
  batch_size: 128
  num_subsets: 1000
  val_batch_size: 128
engine: engine.tweet.FixTensorFusion
exp_name: tweet_concat
train:
  fusion:
    model: model.vanilla_fusion.Concatenate
  fusion_dim: 1536
  hidden_dim: 32
  lr: 0.001
  max_epoch: 100
  weight_decay: 0
